# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d18592efddb75138febd34c49bbad6602c6c04d0a8a27177b2085595cde2f6b354ef041f64337e17b64a940503720e46576f89ec0ee611782c2eb5852d0cb2

test:
  secret_key_base: 093e3a03dd359aa07475fd350eee9dd514ff36f18dedbbdf1fdcb23295a6d124323d1bed0ea75d701cbd878833afcf904b766b5e02b23e5c8f65d510308ae501

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
